### ISSUE TITLE
Account model 관련 issue들

### ISSUE THREAD

**Issue by seyoung755** [todaysFood/todaysFood_issue#14]
작업목록
- [x] Account model 내 is_staff field가 없어서 오류 발생
- [x] uuid field에 대해 migration이 계속 발생하는 문제 발생 
- [x] admin page 접속 안되는 문제

세부사항
리스트 1 : admin 페이지 사용을 위해 createsuperuser를 하면 user model에 is_staff를 할당해주는 부분이 있는데 Model에는 해당 필드가 없어서 오류가 발생하는 것 같습니다. 해결을 위해 is_superuser와 동일한 형식으로 is_staff field를 생성했습니다. 
리스트 2 : account model에서 id 필드의 default가 str(uuid.uuid4) 로 되어 있었는데 이 경우 makemigrations를 해도 migrate가 되지 않고 계속 alter로 uuid가 바뀌는 문제가 발생했습니다. 그래서 default값을 그냥 uuid.uuid4로 수정했습니다. 
리스트 3 : python manage.py createsuperuser로 계정 생성을 했는데 staff가 권한이 없는지 admin 페이지 접속이 안됩니다

1,2 문제는 우선 테스트 하느라 코드 수정 하였는데 확인하시고 의견 남겨주세요~

마일스톤
url

해당 이슈에 맞는 레이블도 달아주세요.

**Comment by jak010** [comment]
해당 이슈는 어느 브랜치를 보면 되나요?

**Comment by seyoung755** [comment]
feature13 참조 부탁드립니다!

**Comment by seyoung755** [comment]
+ 위 브랜치에 jwt token 발급받은 유저에 한하여 api/post 에 접근할 수 있도록 구현하였습니다.
admin page관련해서는 우선 만들어진 user의 is_staff, is_superuser 등의 값을 수동으로 바꿔서 접근하였습니다.
그리고 post에서 jwt 토큰이 없는 유저는 GET 요청도 막고 있는데 구체적인 허용범위(ex. 비로그인 시에도 글을 읽게는 허용할 것인지 등)는 다음 미팅 때 논의해봐야 할 것 같습니다.

**Comment by jak010** [comment]
코드가 변경된 부분에 대해서는 확인했습니다. 다음부터는 작업 시에 에러 내용도 첨부해주시면 좋을 것 같습니다

**Comment by seyoung755** [comment]
넵 확인했습니다
추가로, 권한 인증이 되는 줄 알았는데 테스트할 때 permission을 IsAuthenticated로 설정 안했었나봅니다 .. 
제대로 설정하니 Token 발급받고 Header에 담아 보내도 계속 인증 데이터가 제공되지 않았다는 메시지가 나오네요 .. 원인이 뭘까요?
![image](https://user-images.githubusercontent.com/54302155/119218560-e545cc80-bb1b-11eb-8f5e-6f8201b047fe.png)

**Comment by jak010** [comment]
> 넵 확인했습니다
> 추가로, 권한 인증이 되는 줄 알았는데 테스트할 때 permission을 IsAuthenticated로 설정 안했었나봅니다 ..
> 제대로 설정하니 Token 발급받고 Header에 담아 보내도 계속 인증 데이터가 제공되지 않았다는 메시지가 나오네요 .. 원인이 뭘까요?
> ![image](https://user-images.githubusercontent.com/54302155/119218560-e545cc80-bb1b-11eb-8f5e-6f8201b047fe.png)

해당 작업은 어느 브랜치를 보면 되나요?

**Comment by seyoung755** [comment]
feature-14입니다~
