### ISSUE TITLE
게시판 권한관리 완료 및 User model과의 연결

### ISSUE THREAD

**Issue by seyoung755** [todaysFood/todaysFood_issue#15]
작업목록
- [x] 게시판 권한관리 완료
- [x] User model과 연결

세부사항
리스트 1 : 현재 token 발급은 되지만 verify가 정상적으로 안되는 중임 -> 로그인 시에만 게시판 이용이 가능해지도록 JWT authentication 구현
리스트 2 : Post model에서 사용하는 user와 User model의 user를 연결하여 작성 글 수정이나 삭제 권한을 작성자와 admin user만 가능하도록 구현

마일스톤
https://github.com/todaysFood/todaysFood_issue/milestone/4

해당 이슈에 맞는 레이블도 달아주세요.

**Comment by jak010** [comment]
기본 jwt 인증 라이브러리를 simple-jwt로 변경했습니다. 
작업 브랜치: https://github.com/todaysFood/todaysFood_backend/tree/feature/auth

이야기 나눠볼 내용이 조금 많습니다 날 잡아서 이야기 하는게 좋을 것 같습니다.

**Comment by seyoung755** [comment]
넵 평일 저녁에 시간되실때 말씀해주세요~
