### ISSUE TITLE
백엔드 배포 

### ISSUE THREAD

**Issue by kyupkyup** [todaysFood/todaysFood_issue#20]
작업목록
- [x] nginx 서버에 설치
- [x] nginx 환경설정
- [x] nginx 쟝고 연결
- [x] 테스트

**Comment by seyoung755** [comment]
우선 Feed 관련 API Doc page 업데이트 완료했습니다
https://todaysfood.github.io/API-documents/readme

**Comment by jak010** [comment]
로그인 기능 이상 없네요

**Comment by seyoung755** [comment]
6/20 미팅 : 코드 베이스 개선

- Post model API로 통합 
- API 폴더 내 views.py를 view 폴더 내로 통합
- URL 정렬 및 URL 마지막 '/' 삭제 
- URL 이름 명확하게 ('post 앞에 feed 명기하여 다른 기능과 혼동되지 않도록) + 권한설정 데코레이터로 변경 후 목록조회에 글쓰기는 Feed 하나로 통합, url 불필요한 name 삭제 
- Serializer에 Business 로직 분리하는 것 고민
- Status code 201과 200의 차이 고민 -> api 문서에 반영
- 주석 스타일 : docstring convention 
- 평점 field 상한 값 5로 제한(6 넣어도 동작하는 중)
- 리팩터링 관련 정리

**Comment by jak010** [comment]
## 배포  작업 진행
- nginx 설치
- gunicorn 서비스 스크립트 작성
- nginx와 gunicorn 연결


도메인을 통해 연결하는 부분은 nginx 설정은 잡아뒀는데 기존 도메인 관리가 어떻게 되어있는지 모르겠네요
