### ISSUE TITLE
백엔드 서버 배포 코드 수정 관련

### ISSUE THREAD

**Issue by seyoung755** [todaysFood/todaysFood_issue#23]
작업목록
- [ ] issue #20 관련 코드 수정(URL 수정 및 API 구조 수정)

세부사항
리스트 1 : 지난번에 협의한 리팩토링 관련과 API 구조를 조금 수정했습니다. (issue20 branch)
확인하시고 문제없으면 PR 후 서버에 배포하려고 합니다

마일스톤
url

해당 이슈에 맞는 레이블도 달아주세요.

**Comment by jak010** [comment]
Issue20 브랜치를 develop 브랜치와 비교하면 merge가 안되는 상황입니다. 문제 해결 후에 다시 알려주세요

**Comment by seyoung755** [comment]
넵 저녁에 한번 확인해보겠습니다~

**Comment by seyoung755** [comment]
merge 완료했습니다~!
