### ISSUE TITLE
코드 베이스 정렬

### ISSUE THREAD

**Issue by jak010** [todaysFood/todaysFood_issue#7]
- requirments.txt의 `pytz` 패키지가 설치 과정에서 에러가 납니다.
```sh
$ pip install -r requirement.txt
```
  - Version: python3.8.5 
![image](https://user-images.githubusercontent.com/33048366/117577895-bba5a200-b126-11eb-9eed-9a53b32e51a7.png)
확인 해보시고 댓글에 의견 남겨주세요

**Comment by seyoung755** [comment]
pytz==2020.1 이 맞는 것 같네요 pi는 어디서 오타가 발생한것 같습니다 수정해서 merge해놓겠습니다~

**Comment by jak010** [comment]
> pytz==2020.1 이 맞는 것 같네요 pi는 어디서 오타가 발생한것 같습니다 수정해서 merge해놓겠습니다~

확인했습니다
