### ISSUE TITLE
서버 관련 정보 전달

### ISSUE THREAD

**Issue by seyoung755** [todaysFood/todaysFood_issue#9]
- 도메인 관련
현재 구동되고 있는 api 서버 도메인은 https://www.weatherplace.site 입니다
서버에 접속할 수 있는 pem키 첨부 드립니다

- DB 관련
aws RDS로 MySQL 5.7.31 버전 생성했습니다.
사용자 이름 : root
비밀번호 : -
호스트명 : todayfood-webservice.chjvljwllphp.ap-northeast-2.rds.amazonaws.com
port : 3306

확인하시고 추가로 필요한 사항 있으시면 남겨주세요~

**Comment by seyoung755** [comment]
DB 인스턴스 이름은 todayFood_webservice 입니다~
```python
DATABASES =  {
    'default' : {
	'ENGINE': 'django.db.backends.mysql',
	'NAME': 'todayFood_webservice',
	'USER': 'root',
	'PASSWORD': -
	'HOST': 'todayfood-webservice.chjvljwllphp.ap-northeast-2.rds.amazonaws.com',
	'PORT': '3306',
    }
}
```

**Comment by jak010** [comment]
> * 도메인 관련
>   현재 구동되고 있는 api 서버 도메인은 https://www.weatherplace.site 입니다
>   서버에 접속할 수 있는 pem키 첨부 드립니다
>   [bbs-springboot2-webservice.pem.zip](https://github.com/todaysFood/todaysFood_issue/files/6452176/bbs-springboot2-webservice.pem.zip)
> * DB 관련
>   aws RDS로 MySQL 5.7.31 버전 생성했습니다.
>   사용자 이름 : root
>   비밀번호 : passw0rd
>   호스트명 : todayfood-webservice.chjvljwllphp.ap-northeast-2.rds.amazonaws.com
>   port : 3306
> 
> 확인하시고 추가로 필요한 사항 있으시면 남겨주세요~

서버에 pem키는 확인했습니다 ssh 로 접속할 때 필요한 서버 IP랑 계정정보를 알려주시면 될 것 같아요

**Comment by seyoung755** [comment]
서버 연결 시 아래 정보만 있어도 접속이 되나요? 
ssh -i "bbs-springboot2-webservice.pem" ubuntu@ec2-3-36-171-252.ap-northeast-2.compute.amazonaws.com

추가로 DB연결 되는건 어제 확인했는데 집가서 추가로 확인해보겠습니다

**Comment by kyupkyup** [comment]
이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!

**Comment by seyoung755** [comment]
넵 pem키는 받으신거같으니 삭제했습니다~ db정보도 우선 패스워드는 가려놓을게요 ㅋㅋㅋ pem키 첨부된게 quotation돼서 지안님 comment는 지웠습니다~

**Comment by jak010** [comment]
> 이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!


이슈 저장소를 private으로는 변경 못하나요?

**Comment by kyupkyup** [comment]
> > 이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!
> 
> 이슈 저장소를 private으로는 변경 못하나요?

private으로 바꿀까요? 저희 프로젝트를 보여준다고 할 때 저희가 이슈 관리를 어떻게 하는지도 보여줄 수 있으면 좋을 거 같아서요. 저는 포폴로도 사용해야되서.. ㅎㅎ private으로 바꾼다고 해도 pem key 같은거는 github에 올리지는 않는게 좋을 거 같습니다 ㅎㅎ

**Comment by jak010** [comment]
> > > 이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!
> > 
> > 
> > 이슈 저장소를 private으로는 변경 못하나요?
> 
> private으로 바꿀까요? 저희 프로젝트를 보여준다고 할 때 저희가 이슈 관리를 어떻게 하는지도 보여줄 수 있으면 좋을 거 같아서요. 저는 포폴로도 사용해야되서.. ㅎㅎ private으로 바꾼다고 해도 pem key 같은거는 github에 올리지는 않는게 좋을 거 같습니다 ㅎㅎ

알겠습니다 그럼 필요한 파일은 어떤식으로 공유하는 게 좋을까요?

**Comment by kyupkyup** [comment]
> > > > 이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!
> > > 
> > > 
> > > 이슈 저장소를 private으로는 변경 못하나요?
> > 
> > 
> > private으로 바꿀까요? 저희 프로젝트를 보여준다고 할 때 저희가 이슈 관리를 어떻게 하는지도 보여줄 수 있으면 좋을 거 같아서요. 저는 포폴로도 사용해야되서.. ㅎㅎ private으로 바꾼다고 해도 pem key 같은거는 github에 올리지는 않는게 좋을 거 같습니다 ㅎㅎ
> 
> 알겠습니다 그럼 필요한 파일은 어떤식으로 공유하는 게 좋을까요?

보안상으로 문제될만한 파일은 개인적으로 메일이나 카톡으로 전달하는게 좋을거같고, 그 외에는 그냥 올려주셔도 상관없을거같습니다~~

**Comment by jak010** [comment]
> > > > > 이 저장소는 public이라 pem 키 첨부는 위험합니다. 카톡이나 다른 방법으로 공유해주세요!
> > > > 
> > > > 
> > > > 이슈 저장소를 private으로는 변경 못하나요?
> > > 
> > > 
> > > private으로 바꿀까요? 저희 프로젝트를 보여준다고 할 때 저희가 이슈 관리를 어떻게 하는지도 보여줄 수 있으면 좋을 거 같아서요. 저는 포폴로도 사용해야되서.. ㅎㅎ private으로 바꾼다고 해도 pem key 같은거는 github에 올리지는 않는게 좋을 거 같습니다 ㅎㅎ
> > 
> > 
> > 알겠습니다 그럼 필요한 파일은 어떤식으로 공유하는 게 좋을까요?
> 
> 보안상으로 문제될만한 파일은 개인적으로 메일이나 카톡으로 전달하는게 좋을거같고, 그 외에는 그냥 올려주셔도 상관없을거같습니다~~

네~

**Comment by jak010** [comment]
> 서버 연결 시 아래 정보만 있어도 접속이 되나요?
> ssh -i "bbs-springboot2-webservice.pem" [ubuntu@ec2-3-36-171-252.ap-northeast-2.compute.amazonaws.com](mailto:ubuntu@ec2-3-36-171-252.ap-northeast-2.compute.amazonaws.com)
> 
> 추가로 DB연결 되는건 어제 확인했는데 집가서 추가로 확인해보겠습니다

서버 접속은 확인했습니다

**Comment by seyoung755** [comment]
방금 서버나 로컬에서 RDS 연결되는 걸로 확인했습니다 
보안 규칙때문에 접속이 안되셨나 싶어서 모든 ip에 대해 개방해두었습니다.
 DB 연결되는지 한번 다시 확인 부탁드려요~

**Comment by jak010** [comment]
> 방금 서버나 로컬에서 RDS 연결되는 걸로 확인했습니다
> 보안 규칙때문에 접속이 안되셨나 싶어서 모든 ip에 대해 개방해두었습니다.
> DB 연결되는지 한번 다시 확인 부탁드려요~

네 DB 연결도 확인했으니 해당 이슈는 클로즈 처리합니다 ~
